# Site settings
title: Matthew R. Olm
email: mattolm@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    I'm a PhD Candidate in the Department of Plant and Microbial Biology at UC-Berkeley.
    I study the human microbiome using metagenomics.
url: "https://mrolm.github.io/" # the base hostname & protocol for your site
twitter_username: mattagenolmics
github_username:  mrolm
gems:
    - jekyll-sitemap

# Build settings
markdown: kramdown
